config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, except: [:index, :destroy] do
    resources :board_users, only: [:index]
    resources :experiences, only: [:create, :new]
    resources :day_schedules, only: [:index,:show, :new, :create]
  end

  resources :boards, only: [:destroy]
  resources :day_schedules, only: [:destroy, :update]
  resources :day_schedule_items, only: [:destroy]
  resources :board_users, only: [:destroy, :new, :create]
  resources :experiences, only: [:edit, :update, :destroy]
  resources :connections, only: [:index, :new, :create, :destroy]

  get 'dashboard', to: "pages#dashboard"
  get 'board', to: "pages#user_board", as: :user_boards
  post 'experiences/:id/upvote', to: "experiences#upvote", as: :experience_upvote
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :experiences, dependent: :destroy
  has_many :board_users, dependent: :destroy
  has_many :users, through: :board_users
  has_many :day_schedule_items, through: :experiences, dependent: :destroy
  has_many :day_schedules, through: :day_schedule_items, dependent: :destroy

  validates :place, presence: true
  validates :title, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true

  geocoded_by :place
  after_validation :geocode, if: :will_save_change_to_place?

end

app/models/day_schedule.rb
class DaySchedule < ApplicationRecord
  has_many :day_schedule_items
  has_many :experiences, through: :day_schedule_items
  # has_one :board, through: :experiences
  belongs_to :board

  validates :date, presence: true , uniqueness: { scope: :board }

end

app/controllers/day_schedules_controller.rb
class DaySchedulesController < ApplicationController
  before_action :pundit_sucks

  def index
    @board = Board.find(params[:board_id])
    # raise
    @day_schedules = @board.day_schedules.order(date: :ASC)
    @first_day_schedule = @day_schedules[0]
    @rest_day_schedules = @day_schedules[1..-1]
     # raise
  end

  def show
  end

  def new
  end

  def update
    @day_schedule = DaySchedule.find(params[:id])
    @day_schedule.update(notes: params[:day_schedule][:notes])
    redirect_to board_day_schedules_path(@day_schedule.board)
  end

  def create
    board = Board.find(params[:board_id])
    experience_ids = params[:experiences].gsub('ids=', '').split('&')
    day_schedule = DaySchedule.where(date: params[:day_schedule][:date], board: board).first
    if day_schedule.nil?
       day_schedule = DaySchedule.create(date: params[:day_schedule][:date], board: board)
    end
    experience_ids.each do |id|
      DayScheduleItem.create(experience_id: id, day_schedule: day_schedule)
    end
    session[:date_item] = day_schedule.date
    redirect_to board_day_schedules_path
  end

   def pundit_sucks
    authorize current_user
  end

end

app/views/day_schedules/_experience_card.html.erb
<div class="experience-card mb-2" data-id="<%= experience.id %>">
      <%= image_tag experience.photo, alt: "alttext" %>
      <p class="d-flex justify-content-between mt-1">
        <button type="button" data-toggle="modal" data-target=<%= "#experience#{experience.id}" %>>
          <%= experience.title %>
        </button>
        <i class="fas fa-heart">
          <% if experience.vote > 0 %>(
          <%= experience.vote %>)
          <% end %>
        </i>
      </p>
    </div>

app/views/day_schedules/create.html.erb
<h1>DaySchedule#create</h1>
<p>Find me in app/views/day_schedule/create.html.erb</p>

app/views/day_schedules/index.html.erb
<div class="card-category top-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1530789253388-582c481c54b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
  <div class="banner-text"><%= @board.title %> Itinerary</div>
</div>
<div class="white vh-100">

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="false">
  <div class="carousel-inner">
    <div>
      <% @day_schedules.uniq.each do |day_schedule| %>
      <% if session[:date_item] %>
        <% date = session[:date_item] == day_schedule.date.strftime("%Y-%m-%d")  %>
      <% else %>
        <% date = @day_schedules.uniq[0] == day_schedule %>
      <% end %>
      <div class="carousel-item <%= date ? 'active' : nil %>">
     <!--  <h3 class="text-center"> <%= @board.title %></h3> -->
      <h3 class="text-center py-3"><%= day_schedule.date.strftime("%A, %d %b %Y ") %></h3>
      <!-- notes section -->

      <% if day_schedule.notes %>
        <div class="d-flex justify-content-center">
          <div class="notes text-center mb-4">
            <h6>Day Notes:</h6>
            <%= day_schedule.notes %>
            <i class="far fa-edit edit-note-icon" type="text" data-toggle="modal" data-target="#edit-note<%= day_schedule.id %>"></i>
          </div>
          <div class="modal fade" id="edit-note<%= day_schedule.id %>" tabindex="-1" role="dialog">
             <div class="modal-dialog modal-dialog-centered" role="document">
             <div class="modal-content">
             <div class="modal-header turquoise  d-flex flex-column align-items-center justify-content-center">
                  <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
                  <h5 class="modal-title" id="add-experience-title">Update Day Note</h5>
                  <button type="text" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body text-center">
                  <%= simple_form_for day_schedule do |f| %>
                    <%= f.input :notes %>
                    <%= f.submit class: "btn btn-ghost" %>
                  <% end %>
                </div>
                </div>
             </div>
          </div>
        </div>
      <% else %>
        <div class="new-note text-center mb-5">
          <p type="text" class="" data-toggle="modal" data-target="#add-note<%= day_schedule.id %>">
            Add Day Note <i class="far fa-sticky-note"></i>
          </p>
        </div>

        <!-- Modal add -note -->
        <div class="modal fade" id="add-note<%= day_schedule.id %>" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header turquoise  d-flex flex-column align-items-center justify-content-center">
                <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
                <h5 class="modal-title" id="add-experience-title">Add Day Note</h5>
                <button type="text" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body text-center">
                <%= simple_form_for day_schedule do |f| %>
                  <%= f.input :notes %>
                  <%= f.submit class: "btn btn-ghost" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>


<!--       modal pop-up edit note -->


<!-- end of modal edit note pop up -->





      <!-- notes end -->
      <div class="col-xs-12 d-flex flex-column justify-content-center align-items-center">
      <% day_schedule.day_schedule_items.each do |day_schedule_item| %>
          <!-- Experience Cards -->
        <div class="day-schedule-item-card experience-card mb-2 shadow p-3 mb-5 bg-white" data-id="<%= day_schedule_item.experience.id %>">
          <%= image_tag day_schedule_item.experience.photo, alt: "alttext" %>
          <p class="d-flex justify-content-between mt-1">
            <p type="text" data-toggle="modal" data-target=<%= "#experience#{day_schedule_item.experience.id}" %>>
              <%= day_schedule_item.experience.title %>
            </p>
            <div class="day-schedule-item-delete">
              <%= link_to day_schedule_item_path(day_schedule_item), method: :delete do %>
                <i class="fas fa-times"></i>
              <% end %>
            </div>
          </p>
        </div>
      <% end %>
      </div>
      <div class="d-flex justify-content-center align-items-center mb-5">
      <%= link_to "back to board", board_path(params[:board_id]), class: "btn btn-ghost" %>
      </div>
      </div>
      <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<% if @board.day_schedule_ids == [] %>
<div class="full-screen-with-banner p-3 text-center">
<p>You have not created any itineries yet! Go back to your board to add experiences to a day schedule.</p>
<p class="text-center btn btn-ghost-small"><%= link_to "back to board", board_path(params[:board_id]) %></p>
<% end %>
</div>
</div>

app/views/day_schedules/new.html.erb
<h1>DaySchedule#new</h1>
<p>Find me in app/views/day_schedule/new.html.erb</p>

app/views/day_schedules/show.html.erb
<h1>DaySchedule#show</h1>
<p>Find me in app/views/day_schedule/show.html.erb</p>