config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, except: [:index, :destroy] do
    resources :board_users, only: [:index]
    resources :experiences, only: [:create, :new]
    resources :day_schedules, only: [:index,:show, :new, :create]
  end

  resources :boards, only: [:destroy]
  resources :day_schedules, only: [:destroy, :update]
  resources :day_schedule_items, only: [:destroy]
  resources :board_users, only: [:destroy, :new, :create]
  resources :experiences, only: [:edit, :update, :destroy]
  resources :connections, only: [:index, :new, :create, :destroy]

  get 'dashboard', to: "pages#dashboard"
  get 'board', to: "pages#user_board", as: :user_boards
  post 'experiences/:id/upvote', to: "experiences#upvote", as: :experience_upvote
end

app/views/shared/_board-footer.html.erb
<div class="board-footer d-flex justify-content-center">
  <div class="board-footer-links">
    <div class="notification justify-content-center align-items-center" id="notification" style="display: none">
      0
    </div>
    <% if params[:controller] == 'boards' && params[:action] == 'show' %>
    <%= link_to '#', id: 'new-sched', data: { toggle:'modal', target:'#new-schedule'} do %>
    <i class="far fa-calendar-plus footer-link"></i>
    <% end %>
    <% else %>
    <%= link_to new_board_day_schedule_path(params[:board_id]), id: 'new-sched' do %>
    <i class="far fa-calendar-plus footer-link"></i>
    <% end %>
    <% end %>
    <%= link_to board_day_schedules_path(board_id: params[:id]) do  %>
    <i class="fas fa-route footer-link"></i>
    <% end %>
    <div id="control-div" class="control-div" data-toggle="modal" data-target="#add-experience-form">
      <a id="add-experience-link"><i class="fas fa-plus footer-link"></i></a>
    </div>
    <%= link_to connections_path(board_id: @board.id) do %>
    <i class="fas fa-user-plus footer-link"></i>
    <% end %>
    <!-- Popover button -->

      <i class="fas fa-search footer-link" data-toggle="popover">
      </i>

    <!-- End of popover -->
    <!-- Popover content -->
    <div id='search-form' hidden>
      <div class='popover-div text-center'>
        <%= simple_form_for [@board, @experience], url: board_path(@board), method: :get do |f| %>
        <%= f.association :category, label: false, :include_blank => "See all" %>
        <%= f.submit "Search", class: " btn btn-ghost-peach mb-2" %>
        <% end %>
      </div>
      <!-- End of popover content -->
    </div>
  </div>
</div>
  <div class="modal fade" id="new-schedule" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content text-center">
        <div class="modal-header turquoise d-flex justify-content-center align-items-center flex-column text-center">
          <div><%= image_tag "_triangle-marker.svg", alt: "alttext" %></div>
          <h5 class="modal-title" id="exampleModalLongTitle">Pick a date</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@board, DaySchedule.new] do |f| %>
          <%= f.input :date, html5: true, as: :date %>
          <%= hidden_field_tag 'experiences', 'ids=' %>
          <%= f.submit class: "btn btn-ghost" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_day-schedule-footer.html.erb
<div class="board-footer d-flex justify-content-center">
  <div class="day-schedule-footer-links">
    <div class="notification d-flex justify-content-between align-items-center">
      <%= link_to '#', id: 'new-sched', data: { toggle:'modal', target:'#new-schedule'} do %>
        <i class="far fa-sticky-note"></i>
      <% end %>
      <%= link_to board_path(params[:board_id]) do %>
        <i><%= image_tag "_triangle-marker.svg", alt: "alttext" %></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>