config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, except: [:index, :destroy] do
    resources :board_users, only: [:index]
    resources :experiences, only: [:create, :new]
    resources :day_schedules, only: [:index,:show, :new, :create]
  end

  resources :boards, only: [:destroy]
  resources :day_schedules, only: [:destroy, :update]
  resources :day_schedule_items, only: [:destroy]
  resources :board_users, only: [:destroy, :new, :create]
  resources :experiences, only: [:edit, :update, :destroy]
  resources :connections, only: [:index, :new, :create, :destroy]

  get 'dashboard', to: "pages#dashboard"
  get 'board', to: "pages#user_board", as: :user_boards
  post 'experiences/:id/upvote', to: "experiences#upvote", as: :experience_upvote
end

app/models/experience.rb
class Experience < ApplicationRecord
  acts_as_votable
  belongs_to :board
  belongs_to :user
  belongs_to :category
  has_many :day_schedule_items
  has_many :day_schedules, through: :day_schedule_items


  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :title, presence: true
  validates :user_id, presence: true
  validates :category_id, presence: true
end

app/controllers/experiences_controller.rb
require 'open-uri'
require 'json'

class ExperiencesController < ApplicationController
  before_action :pundit_sucks


  def nearby_search_api(query, coords)
    key = "&key=#{ENV['GOOGLE_MAPS_KEY']}"
    location = "&location=#{coords[0]},#{coords[1]}"
    radius = "&radius=50000"
    language = "&language=#{session["language"]}"
    places_endpoint = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword="
    api_call = places_endpoint+query+location+radius+language+key
    uri = open(api_call).read
    results = JSON.parse(uri)
    list = results["results"][0..4]
    return list
  end

  def find_place_api(query, coords)
    endpoint = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
    search_query = "input=#{query}&inputtype=textquery"
    fields = "&fields=place_id,name,formatted_address,photos,geometry"
    location = "&locationbias=point:#{coords[0]},#{coords[1]}"
    key = "&key=#{ENV['GOOGLE_MAPS_KEY']}"
    language = "&language=en"
    api_call = endpoint+search_query+fields+location+language+key
    uri = open(api_call).read
    results = JSON.parse(uri)
    return results["candidates"]
  end

  def details_api(place_id)
   key = "&key=#{ENV['GOOGLE_MAPS_KEY']}"
   details_endpoint = "https://maps.googleapis.com/maps/api/place/details/json?place_id=#{place_id}&key=#{ENV['GOOGLE_MAPS_KEY']}"
   query_fields = "&fields=name,geometry,formatted_address,photos,rating,opening_hours,website,url,price_level,international_phone_number"
   api_call = details_endpoint+query_fields
   uri = open(api_call).read
   results = JSON.parse(uri)["result"]
   details = {}
   details[:user_id] = current_user.id
   details[:board_id] = @experience[:board_id]
   details[:category_id] = @experience[:category_id]
   details[:title] = @experience[:title]
   details[:description] = @experience[:description]
   details[:latitude] = results["geometry"]["location"]["lat"] || nil
   details[:longitude] = results["geometry"]["location"]["lng"] || nil
   details[:address] = results["formatted_address"] || nil
   details[:opening_hours] = results["opening_hours"] ? results["opening_hours"]["weekday_text"] : nil
   details[:phone_number] = results["international_phone_number"] || nil
   details[:rating] = results["rating"] || nil
   details[:google_url] = results["url"] || nil
   details[:website] = results["website"] || nil
   details[:price_level] = results["price_level"] || nil
   photo_refs = results["photos"].map {|each| each["photo_reference"]}[0..4] if results["photos"]
   details[:photos] = photo_refs.map {|pic| "https://maps.googleapis.com/maps/api/place/photo?maxwidth=1600&photoreference=#{pic}&key=#{ENV['GOOGLE_MAPS_KEY']}"} if photo_refs
   return details
  end

   helper_method :details_api

  def new
    @board = Board.find(params[:board_id])
    @experience = Experience.new(experience_params)
    city = params[:level] == 'city'
    board_is_city = @board.level == ("city" || "locality") ? true : false
    city_all_along = city && board_is_city
    if params[:cityname].present?
      specified_city = Geocoder.search(params[:cityname])
      specified_city_coords = [specified_city[0].data["geometry"]["location"]["lat"], specified_city[0].data["geometry"]["location"]["lng"]]
      scnelat = specified_city[0].data["geometry"]["bounds"]["northeast"]["lat"]
      scnelng = specified_city[0].data["geometry"]["bounds"]["northeast"]["lng"]
      scswlat = specified_city[0].data["geometry"]["bounds"]["southwest"]["lat"]
      scswlng = specified_city[0].data["geometry"]["bounds"]["southwest"]["lng"]
      specified_city_bounds = [[scnelat, scnelng], [scswlat, scswlng]]
    end
    board_bounds = [[@board.ne_lat, @board.ne_lng],[@board.sw_lat, @board.sw_lng]]
    @map_bounds = params[:cityname].present? ? specified_city_bounds : board_bounds
    query = URI.escape(@experience.title)
    board_coords = [@board.latitude, @board.longitude]
    @coords = !city || city_all_along ? board_coords : specified_city_coords
    @list = city ? nearby_search_api(query, @coords) : find_place_api(query, @coords)
    @places = @list.map do |each|
      { title:  @experience.title,
        category_id: @experience.category_id,
        coords: [each["geometry"]["location"]["lat"].to_f, each["geometry"]["location"]["lng"].to_f],
        photos: (each["photos"][0]["photo_reference"] if each["photos"]) }
    end
    @markers = @list.map {|each| [each["geometry"]["location"]["lat"].to_f, each["geometry"]["location"]["lng"].to_f] }
    @photo_refs = @list.map do |each|
      if each["photos"]
        each["photos"][0]["photo_reference"]
      end
    end
    @photo_refs.delete(nil)
    @photos = @photo_refs.map {|pic| "https://maps.googleapis.com/maps/api/place/photo?maxwidth=1600&photoreference=#{pic}&key=#{ENV['GOOGLE_MAPS_KEY']}"}
  end

  def create
    exp = Experience.new(experience_params)
    exp.user = current_user
    exp.board_id = params[:board_id]
    exp.save
    if exp.save!
    redirect_to board_path(exp.board)
    else
      raise
    end
  end

  def index
    category_id = params["experience"]["category_id"]
    @category_name = Category.find(category_id).name.capitalize
    @board = Board.find(params["board_id"])
    @experiences = @board.experiences.where(category_id: category_id)
  end


  def edit
  end

  def update
  end

  def upvote

    @experience = Experience.find(params[:id])
    old_count = @experience.votes_for.count

    @experience.vote_by :voter => current_user
    new_count = @experience.votes_for.count

    @voted = old_count != new_count

    respond_to do |format|
        # format.html { redirect_to restaurant_path(@restaurant) }
        format.js
      end

  end

  private

  def pundit_sucks
    authorize current_user
  end

  def experience_params
    params.require(:experience).permit(:longitude, :latitude, :title, :description, :photo, :board_id, :user_id, :category_id, :address, :rating, :opening_hours, :price_level, :phone_number, :website, :google_url)
  end
end

app/views/experiences/edit.html.erb
<h1>Experiences#edit</h1>
<p>Find me in app/views/experiences/edit.html.erb</p>

app/views/experiences/index.html.erb
<h3>Experiences of Category: <%= @category_name %> on <%= @board.title %>
</h3>
  <% @experiences.each do |experience| %>
  <!-- Experience Cards -->

    <div class="experience-card mb-2" data-id="<%= experience.id %>">
      <% if experience.photo %>
      <%= image_tag experience.photo, alt: "alttext" %>
      <% else %>
      <%= image_tag "https://images.unsplash.com/photo-1477505982272-ead89926a577?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60", alt: "alttext" %>
      <% experience.photo = "https://images.unsplash.com/photo-1477505982272-ead89926a577?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" %>
      <% experience.save %>
      <% end %>
 <!--      <div class="d-flex justify-content-between"> -->
        <div class="d-flex justify-content-between mt-1">
          <button style="font-size: 12px" type="button" id="<%= "button#{experience.id}" %>" data-toggle="modal" data-target=<%= "#experience#{experience.id}" %>>
            <%= experience.title %>
          </button>
        <!--   <div class="d-flex align-items-center" style="font-size: 12px"> -->
            <p data-id="<%= experience.id %>" class="d-flex align-items-center m-0" style="font-size: 12px">
              <%= experience.votes_for.count %>
              <%= link_to experience_upvote_path(experience),class:"fas fa-heart heart-like ml-1",method: :post, remote: true, style:"display: block" do %>
              <% end %>
            </p>
       <!--    </div> -->
        </div>
<!--       </div> -->

    </div>
<% end %>
<%= render 'shared/board-footer' %>

app/views/experiences/new.html.erb
<div class="lol-container turquoise">
  <div class="card-category top-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1530789253388-582c481c54b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
    <div class="banner-text"><%= @experience.title %><br>
    </div>

  </div>
  <div class="card-container">

  <div id="map" style="height: 30vh; width: 100%; overflow: hidden;" data-bounds="<%= @map_bounds.to_json %>" data-center="<%= @coords.to_json %>" data-markers="<%= @markers.to_json %>" data-places="<%= @places.to_json %>" data-pin-drop-marker="<%= asset_path 'pin-drop-marker.svg' %>" data-green-marker="<%= asset_path 'triangle2.svg' %>">
  </div>
  <div class="d-flex align-items-center justify-content-center turquoise" style="height: 70px;">
    <h6 class="text-center" style=" font-family: 'open sans'; font-weight: bolder; color: white; font-size: 18px;">We have found these options for you.</h6>
  </div>

    <div class="card-columns">

      <% @list.each_with_index do |each, i|  %>
      <div class="experience-card mb-2">
        <% if @photos[i] %>
        <%= image_tag @photos[i], alt: "alttext" %>
        <% else %>
        <%= image_tag "https://www.battlegroundindy.com/wp-content/uploads/2019/01/no-image-770x466.jpg", alt: "alttext" %>
        <% end %>
        <div>
          <div>
            <div class="text-center m-0" style="font-size: 14px">
              <%= each["name"] %>
            </div>
          </div>
          <div class="" , style="font-size: 12px; font-weight: lighter;">
            <div class="text-center">
              <%= each["vicinity"] %>
            </div>
          </div>
          <!--           <p>Price Level:
            <%#= each["price_level"] %>
          </p> -->
          <div class="w-100 d-flex justify-content-center mt-1">
            <a href="#" data-toggle="modal" data-target="#confirm-experience" ><i class="fas fa-plus add-experience"></i></a>
            <%#= link_to "create", "#", class: "btn btn-ghost-small mt-1",
           data: {
            toggle: "modal",
            target: "#confirm-experience"
            } %>
          </div>
        </div>
      </div>
      <!-- Confirm modal -->
      <div class="modal fade" id="confirm-experience" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content text-center">
            <div class="modal-header turquoise d-flex justify-content-center align-items-center flex-column">
              <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
              <h5 class="modal-title" id="exampleModalLongTitle">Please Confirm</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-center">
             <!--  <div class="card vw-100" > -->
                <%# @photos.each do |pic| %>
                <%#= image_tag pic, alt: "alttext", size: "400x200"%>
                <%# end %>
             <!--    <div class="card-body"> -->
                  <%= simple_form_for [@board, @experience] do |f| %>
                  <% modelo = details_api(each["place_id"]) %>
                  <h5 class="card-title">
                    <%= f.input :title, label: "So we're going to:" %>
                  </h5>
                  <div class="card-text">
                    <%= f.input :description, label: "Tell your friends!:" %>
                    <%= f.association :category %>
                    <%= f.input :address, input_html: {value: modelo[:address]}, readonly: true %>
                    <%= f.input :phone_number, input_html: {value: modelo[:phone_number]}, readonly: true %>
                    <% exp_rating = modelo[:rating] ? "☆" * modelo[:rating].to_i : "n/a" %>
                    <%= f.input :rating, as: :hidden, input_html: {value: modelo[:rating]}, readonly: true %>
                    <%= f.label :rating %>
                    <input type="text" readonly="readonly" class="form-control readonly" id="exp-rating" value="<%= exp_rating %>">
                    <% price =  modelo[:price_level] ? "$" * modelo[:price_level].to_i : "n/a"  %>
                    <%= f.input :price_level, as: :hidden, input_html: {value: modelo[:price_level]}, readonly: true %>
                    <%= f.label :price_level %>
                    <input type="text" readonly="readonly" class="form-control readonly" id="exp-price-level" value="<%= price %>">
                    <%= f.input :google_url, as: :hidden, input_html: { value: modelo[:google_url]}, readonly: true %>
                    <%= link_to "reviews", modelo[:google_url] %>
                    <i class="fas fa-external-link-alt"></i>
                    <%= f.input :website, as: :hidden, input_html: {value: modelo[:website]}, readonly: true %>
                    <%= link_to "website", modelo[:website] %>
                    <i class="fas fa-external-link-alt"></i>
                    <%= f.input :latitude, as: :hidden, input_html: {value: modelo[:latitude]} %>
                    <%= f.input :longitude, as: :hidden, input_html: {value: modelo[:longitude]} %>
                    <% exp_pic = modelo[:photos] ? modelo[:photos].sample : "https://www.battlegroundindy.com/wp-content/uploads/2019/01/no-image-770x466.jpg"  %>
                    <%= f.input :photo, as: :hidden, input_html:{value: exp_pic} %>
                    <%= f.button :submit, "Confirm", class: "btn btn-ghost" %>
                    <% end %>
                  </div>
                    <%#= button_to "Confirm", board_experiences_path %>
           <!--      </div> -->
          <!--     </div> -->
            </div>
          </div>
        </div>
      </div>
      <!-- end of modal shit -->
      <!-- End of loop -->
      <% end %>

      <div class="experience-card mb-2">
        <%= image_tag "https://images.unsplash.com/photo-1531171596281-8b5d26917d8b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80", alt: "alttext", style: "background: $peach" %>
        <div>
          <p class="text-center m-0" style="font-size: 12px">None of these?</p>
          <p class="text-center m-0" style="font-size: 12px">Click below to make your own</p>
          <div class="w-100 d-flex justify-content-center">
            <a href="#" data-toggle="modal" data-target="#create-experience"><i class="fas fa-plus add-experience"></i></a>
            <%#= link_to "Create", "#", class: "btn btn-ghost-small mt-1 text-center",
          data: {
            toggle: "modal",
            target: "#create-experience"
            } %>
          </div>
        </div>
      </div>
       </div>
      <!-- Confirm modal -->
      <div class="modal fade" id="create-experience" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-huge modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header d-flex justify-content-center align-items-center flex-column turquoise">
              <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
              <h5 class="modal-title" id="exampleModalLongTitle">Please Confirm</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="form" style="width: 100%;">
                  <%# @photos.each do |pic| %>
                  <%#= image_tag pic, alt: "alttext", size: "400x200"%>
                  <%# end %>
                    <div class="p-3 text-center">
                      <%= simple_form_for [@board, @experience] do |f| %>
                      <%= f.input :title, placeholder: @experience.title %>
                      <%= f.input :description, placeholder: @experience.description  %>
                      <%= f.input :opening_hours, placeholder: "9 to 22" %>
                      <%= f.input :latitude, as: :hidden, input_html: {id: 'formLat'}%>
                      <%= f.input :longitude, as: :hidden, input_html: {id: 'formLng'} %>
                      <%= f.label "location" %>
                      <input type="text" class="form-control mb-3" id="exp-location" placeholder="Pin the map below">
                    </div>
                      <div id="small-map" style="height: 300px;">
                      </div>
                    <div class="p-3 text-center">
                      <%= f.input :price_level, label: "price", hint: "1 to 4", class: "mt-3" %>
                      <%= f.association :category %>
                      <%= f.input :photo %>
                      <%= f.button :submit, class: "btn btn-ghost" %>
                      <% end %>
                    </div>
                  <!-- end of form--></div>

                <!-- end of map -->
              </div>
              <!-- end of row -->
              </div>
              <!-- end of modal-bodyß -->
            </div>
            <!-- end of modal-content -->
          </div>
          <!-- end of modal-dialog -->
        </div>
        <!-- end of modal period -->

    </div>
  </div>
</div>
  <!-- map shit -->
<!--   <div id="map" style="height: 30vh; width: 100%; overflow: hidden;" data-center="<%= @coords.to_json %>" data-markers="<%= @markers.to_json %>" data-places="<%= @places.to_json %>">
  </div> -->

  <!-- end of map shit -->

<%= content_for :map_js do  %>
<%= javascript_pack_tag 'initMap2' %>
<% end %>

app/views/experiences/update.html.erb
<h1>Experiences#update</h1>
<p>Find me in app/views/experiences/update.html.erb</p>

app/views/experiences/upvote.js.erb
function upvote(){
  if ( <%= @voted %> ) {
    let id = "<%= @experience.id %>"
    let counter = document.querySelector(`p[data-id='${id}']`)
    let value = parseInt(counter.innerText, 10)
    counter.innerText = value + 1
    console.log(counter)
  }
}

upvote()