config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, except: [:index, :destroy] do
    resources :board_users, only: [:index]
    resources :experiences, only: [:create, :new]
    resources :day_schedules, only: [:index,:show, :new, :create]
  end

  resources :boards, only: [:destroy]
  resources :day_schedules, only: [:destroy, :update]
  resources :day_schedule_items, only: [:destroy]
  resources :board_users, only: [:destroy, :new, :create]
  resources :experiences, only: [:edit, :update, :destroy]
  resources :connections, only: [:index, :new, :create, :destroy]

  get 'dashboard', to: "pages#dashboard"
  get 'board', to: "pages#user_board", as: :user_boards
  post 'experiences/:id/upvote', to: "experiences#upvote", as: :experience_upvote
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :experiences, dependent: :destroy
  has_many :board_users, dependent: :destroy
  has_many :users, through: :board_users
  has_many :day_schedule_items, through: :experiences, dependent: :destroy
  has_many :day_schedules, through: :day_schedule_items, dependent: :destroy

  validates :place, presence: true
  validates :title, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true

  geocoded_by :place
  after_validation :geocode, if: :will_save_change_to_place?

end

app/controllers/boards_controller.rb
require 'open-uri'
require 'nokogiri'

class BoardsController < ApplicationController
  before_action :set_board, except: [:new, :create]

  def show
    authorize @board
    category_icons = ['🍺', '🧗‍♀️', '👯‍♀️', '🏀', '🗼', '🎁', '⛩', '📺']
    session[:language] = 'en'
    @coords = [@board.latitude.to_f, @board.longitude.to_f]
    @board_users = @board.users

    if params[:experience] && params[:experience]["category_id"].present?
      @experiences = @board.experiences.where(category_id: params[:experience][:category_id])
    else
      @experiences = @board.experiences
    end
    @experience = Experience.new
    @experience.board_id = @board
    @experience.user_id = current_user
    @map_center = [@board.latitude.to_f, @board.longitude.to_f]
    @map_bounds = [[@board.ne_lat, @board.ne_lng],[@board.sw_lat, @board.sw_lng]]
    @markers = []
    @places = @experiences.map do |each|
      {title: each.title,
       description: each.description,
       coords: [each.latitude.to_f, each.longitude.to_f],
       category_id: each.category_id,
       id: each.id}
    end
    @experiences.each do |e|
      @markers << [e.latitude.to_f, e.longitude.to_f]
    end

    url = "https://api.openweathermap.org/data/2.5/weather?lat=#{@board.latitude}&lon=#{@board.longitude}&APPID=#{ENV['OPENWEATHER']}"
    file = open(url).read
    @data = JSON.parse(file)

    @country_code = @data["sys"]["country"]
    @city = @data["name"]

    @currency_code = CountryCode.where(country_code: @country_code).first.currency_code
    @country = CountryCode.where(country_code: @country_code).first.country
    country_url = "https://www.lonelyplanet.com/#{@country}"

    if @board.description == nil
    lonelyplanet_html = open(country_url).read
    lonelyplanet_data = Nokogiri::HTML(lonelyplanet_html)
    @caption = lonelyplanet_data.search('.featured p').text.strip
    @board.description = @caption
    @board.save
    end

    curr_conv_url ="https://free.currconv.com/api/v7/convert?q=GBP_#{@currency_code}&compact=ultra&apiKey=#{ENV['CURR_CONV_KEY']}"
    curr_conv_file = open(curr_conv_url).read
    @conversion = JSON.parse(curr_conv_file)
  end

  def new
    authorize current_user
    @board = Board.new
  end

  def geocode(place)
    result = Geocoder.search(place)
    data = {}
    data[:ne_lat] = result[0].data["geometry"]["bounds"]["northeast"]["lat"]
    data[:ne_lng] = result[0].data["geometry"]["bounds"]["northeast"]["lng"]
    data[:sw_lat] = result[0].data["geometry"]["bounds"]["southwest"]["lat"]
    data[:sw_lng] = result[0].data["geometry"]["bounds"]["southwest"]["lng"]
    case result[0].data["types"][0]
    when "locality" then data[:level] = "city"
    when "country" then data[:level] = "country"
    when "continent" then data[:level] = "continent"
    when "administrative_area_level_1" then data[:level] = "city"
    when "establishment" then data[:level] = "geographic area"
    end
    return data
  end

  def create
    authorize current_user
    @board = Board.new
    @board.place = params[:board]["place"]
    @board.title = params[:board]["title"]
    data = geocode(@board.place)
    @board.ne_lat = data[:ne_lat]
    @board.ne_lng = data[:ne_lng]
    @board.sw_lat = data[:sw_lat]
    @board.sw_lng = data[:sw_lng]
    @board.level = data[:level]
    if @board.valid?
    @board.save
    @board_user = BoardUser.create(board_id: @board.id, user_id: current_user.id, admin: true)
    redirect_to board_path(@board)
    else
    render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/destroy.html.erb
<h1>Boards#destroy</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/new.html.erb
<div class="peach vh-100">
<div class="card-category top-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1530789253388-582c481c54b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
  Where are you going?
</div>

<!-- <div>
  <div class="search">
    <input type="text" class="searchTerm" placeholder="City name">
    <button type="submit" class="searchButton">
      <i class="fa fa-search"></i>
    </button>
  </div>
</div> -->
<!--     <div class="search-form d-block">
      <form action="/boards" method="post" >
        <input class="form-control string required" type="text" name="query" id="place" placeholder="city" />
        <button name="button" type="submit" class="btn btn-flat"><i class="fas fa-search"></i></button>
      </form>
    </div>
 -->
<!-- <div class="botton">
  <a class="btn btn-gradient" href="#">Create New Board</a>
</div>
</div> -->


<div class="p-3 new-board-form text-center">
  <div class="p-3 mt-5" style="background: white">
  <%= simple_form_for @board do |f| %>
      <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
    <%= f.input :place, label: "Destination" %>
      <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
    <%= f.input :title, label: "Name your Board" %>
    <%= f.submit "Create Board", class: "btn btn-ghost" %>
  <% end %>
  </div>
</div>
</div>

app/views/boards/show.html.erb
<!-- <div class="container"> -->
<div class="card-category top-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1530789253388-582c481c54b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
  <div class="banner-text">
    <%= @board.title %></div>
</div>
<div class="d-none" id="board-show"></div>
<div class="d-flex px-3 pb-3 pt-5 justify-content-center align-items-center avatar-div" style="background: white">
  <%= link_to board_board_users_path(@board) do  %>
  <% @board_users.each do |user| %>
  <%= cl_image_tag user.avatar, class: "avatar" %>
  <!--        <img class="avatar" alt="avatar" src=<%=user.avatar %> /> -->
  <% end %>
  <% end %>
  <%= link_to connections_path(board_id: @board.id), class: "d-none" do %>
  <div class="d-flex justify-content-center align-items-center ml-1"><i class="fas fa-plus-circle add-friend-circle avatar" , style="font-size: 40px"></i></div>
  <% end %>
</div>
<!--   <div class="turquoise p-3"> -->
<div class="text-center px-3 pt-3 pb-0" style="background: white">
  <% if @board.description %>
  <p class="board-description m-0">
    <%= @board.description %>
  </p>
  <% end %>
</div>
<!--   </div> -->
<div>
  <!-- <div class="white p-3"> -->

  <div class="weather-currency d-flex justify-content-center", style="background-color: white" >
    <div class="pb-3 pr-1 pl-3 pt-3" style="width: 50vw">

      <!--       <h6 class="text-center">Currency</h6> -->
      <div class="d-flex justify-content-around currency-div align-items-center">
        <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTti0kg8lO5BfHPIUl3faN76HVqwHewN5hywcENXZ8Gbu9Wf5_L_g&s", alt: "alttext", style: "height:55px; width:55px" %>
        <div class="d-flex justify-content-around align-items-center flex-column p-2 currency-div w-50">
          <div>1 GBP</div>
          <div> = </div>
          <div>
            <%= @conversion["GBP_#{@currency_code}"].to_f.round(2) %>
            <%=" #{@currency_code}"%>
          </div>
        </div>
      </div>
    </div>


    <div class="pb-3 pl-1 pr-3 pt-3" style="width: 50vw">

      <!--  <h6 class="text-center">Weather</h6> -->
      <div class="weather-icon d-flex justify-content-around align-items-center p-1">
        <%= image_tag "https://openweathermap.org/img/wn/#{@data['weather'][0]['icon']}@2x.png", alt: "weather icon" %>
        <div>
          <div>
            <%= (@data['main']['temp'].to_f - 273.15).round(0)%> °C
          </div>
          <br>
          <%= @data['weather'][0]['main'] %>
        </div>
      </div>
    </div>
  </div>
  <!--   </div> -->
</div>
<!-- <div class="p-3 py-4 peach"> -->
<div id="map" style="height: 70vh; width: 100%; overflow: hidden;" data-center="<%= @coords.to_json %>" data-bounds="<%= @map_bounds.to_json %>"data-markers="<%= @markers.to_json %>" data-places="<%= @places.to_json %>" data-pin-drop-marker="<%= asset_path 'pin-drop-marker.svg' %>" data-blue-marker="<%= asset_path 'triangle1.svg' %>" data-green-marker="<%= asset_path 'triangle2.svg' %>" data-indigo-marker="<%= asset_path 'triangle3.svg' %>" data-orange-marker="<%= asset_path 'triangle4.svg' %>" data-pink-marker="<%= asset_path 'triangle5.svg' %>" data-red-marker="<%= asset_path 'triangle6.svg' %>" data-yellow-marker="<%= asset_path 'triangle7.svg' %>" data-grey-marker="<%= asset_path 'triangle8.svg' %>" data-black-marker="<%= asset_path 'triangle9.svg' %>">
</div>
<!-- </div> -->
<!-- </div> -->
<!-- Summary of board location -->
<!-- end of board summary -->
<!-- start of iteration for experience cards and modal pop-ups -->
<div class="card-columns">
  <% @experiences.each do |experience| %>
  <!-- Experience Cards -->
  <div class="experience-card mb-2" data-id="<%= experience.id %>">
    <% if experience.photo %>
    <%= image_tag experience.photo, alt: "alttext" %>
    <% else %>
    <%= image_tag "https://images.unsplash.com/photo-1477505982272-ead89926a577?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60", alt: "alttext" %>
    <% experience.photo = "https://images.unsplash.com/photo-1477505982272-ead89926a577?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" %>
    <% experience.save %>
    <% end %>
    <!--      <div class="d-flex justify-content-between"> -->
    <div class="d-flex justify-content-between mt-1">
      <p style="font-size: 12px" type="text" id="<%= " button#{experience.id}" %>" data-toggle="modal" data-target=
        <%= "#experience#{experience.id}" %>>
        <%= experience.title %>
      </p>
      <!--   <div class="d-flex align-items-center" style="font-size: 12px"> -->
      <p data-id="<%= experience.id %>" class="d-flex align-items-center m-0" style="font-size: 12px">
        <%= experience.votes_for.count %>
        <%= link_to experience_upvote_path(experience),class:"fas fa-heart heart-like ml-1",method: :post, remote: true, style:"display: block" do %>
        <% end %>
      </p>
      <!--    </div> -->
    </div>
    <!--       </div> -->
  </div>
  <!-- experience card end -->
  <!-- modal experience card pop-up -->
  <div class="modal fade" id="experience<%= experience.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header peach d-flex justify-content-center align-items-center flex-column">
          <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
          <h5 class="modal-title d-flex justify-content-center align-items-center w-100" id="exampleModalLongTitle">
            <%= experience.title %>
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body d-flex justify-content-center experience-modal">
          <div class="experience-card shadow p-3 mb-5 bg-white" style="width: 18rem;">
            <%= image_tag experience.photo, alt: "alttext" %>
            <div class="card-body">
              <%= cl_image_tag experience.user.avatar, alt: "alttext", class: "avatar" %>
              <ul class="list-unstyled ">
                <li class="my-1 pb-3 border-bottom text-center" style="font-weight: bolder">
                  <%= experience.description %>
                </li>
                <% if experience.rating %>
                <li class="border-bottom py-1 my-1 text-center">
                  <% experience.rating.to_i.round(0).times do %>
                  <i class="fas fa-star"></i>
                  <% end %>
                </li>
                <% end %>
                <% if experience.category %>
                <li class="d-flex justify-content-between my-1 py-1 text-right border-bottom">
                  <i class="fas fa-th-large"></i>
                  <%= experience.category.name %>
                </li>
                <% end %>
                <% if experience.address %>
                <li class="d-flex justify-content-between my-1 py-1 text-right border-bottom">
                  <i>
                    <%= image_tag "small-triangle.svg", alt: "alttext" %></i>
                  <!-- <i class="fas fa-caret-down"></i> -->
                  <%= experience.address %>
                </li>
                <% end %>
                <% if experience.opening_hours %>
                <li class="d-flex justify-content-between my-1 border-bottom">
                  <i class="far fa-clock"></i>
                  <%= experience.opening_hours %>
                </li>
                <% end %>
                <% if experience.price_level && experience.price_level.to_i > 0 %>
                <li class="border-bottom py-1 my-1">
                  <% experience.price_level.to_i.times do %>
                  <i class="fas fa-dollar-sign"></i>
                  <% end %>
                </li>
                <% end %>
                <% if experience.phone_number %>
                <li class="d-flex justify-content-between align-items-center my-1 py-1 border-bottom">
                  <i class="fas fa-phone"></i>
                  <%= experience.phone_number %>
                </li>
                <% end %>
                <% if experience.google_url %>
                <li class="d-flex justify-content-between align-items-center border-bottom my-1 py-1">
                  <i class="far fa-comments"></i>
                  <div>
                    <%= link_to "reviews", experience.google_url %><i class="fas fa-external-link-alt ml-1"></i></div>
                </li>
                <% end %>
                <% if experience.website %>
                <li class="d-flex justify-content-between align-items-center border-bottom my-1 py-1">
                  <i class="fas fa-globe"></i>
                  <div>
                    <%= link_to "website", experience.website %><i class="fas fa-external-link-alt ml-1"></i></div>
                </li>
                <% end %>
                <li class="d-flex justify-content-between align-items-center border-bottom my-1 py-1">
                  <i class="fas fa-heart"></i>
                  <p class="m-0">
                    <%= experience.votes_for.count %>friends liked this</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--   end of modal pop-up -->
  <% end %>
</div>
<!-- end of experience cards and modal pop-up iteration  -->
</div>
<div class="modal fade" id="add-experience-form" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header turquoise  d-flex flex-column align-items-center justify-content-center">
        <%= image_tag "_triangle-marker.svg", alt: "alttext" %>
        <h5 class="modal-title" id="add-experience-title">Add Experience</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">

        <%= simple_form_for [@board, @experience], method: :get, url: new_board_experience_path(@board) do |f| %>
        <%= f.input :title, label: "What are we doing?" %>
        <%= f.input :description, label: "Convince your friends!" %>
        <%= f.association :category, include_blank: false %>


        <%#= o.input :level, as: :radio_buttons, collection: [['City' , 'city'],['Whole map', 'map']],label: 'Where to look?' %>
        <p>Where should i search?</p>
  <div class="d-flex justify-content-center">
        <div  class="text-left">
        <input type="radio" name="level" value="map" checked> Whole map<br><br>
        <input type="radio" name="level" value="city"> City <input type="text" name="cityname" class="city-input-field" /><br><br>
        </div>
  </div>


        <%= f.button :submit, class: "btn btn-ghost mb-3" %>
        <% end %>


      </div>
    </div>
  </div>
</div>
<%  if params[:experience] && params[:experience]["category_id"].present? %>
<div class="category-search-div w-100">
  <div class="text-center search-footer">All
    <%= Category.find(params[:experience][:category_id]).name %> experiences</div>
</div>
<% end %>
<%= render 'shared/board-footer' %>
<%= content_for :map_js do  %>
<%= javascript_pack_tag 'initMap' %>
<% end %>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>